
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP (for certbot redirect and fallback)
      - "443:443"    # HTTPS
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro   # Mount certs
      - /var/www/certbot:/var/www/certbot      # Required for challenge
    depends_on:
      - app
    networks:
      - laravel

  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - laravel
    volumes:
      - mongodbdata:/data/db

networks:
  laravel:

volumes:
  mongodbdata:
